void CompareReweightedDist(Double_t pTmin=2, Double_t pTmax=3, TString dist="Prompt", Double_t d0min=-200, Double_t d0max=200, Double_t ratiomin=0.8, Double_t ratiomax=1.2) {

  gStyle->SetPadLeftMargin(0.16);
  gStyle->SetPadBottomMargin(0.12);
  gStyle->SetOptStat(0);
  
  TString infilename=Form("ImpPar%s_%0.f-%0.f",dist.Data(),pTmin,pTmax);
  TString infilenamePtRew=infilename+"_PtRew";
  const char* funcname = Form("ImpPar%sFunc",dist.Data());
  TString outfilename=infilename+"_PtRewComp.eps";
  TString dist2=dist;
  if(dist=="TrueFD") dist2="TrueBfeed";
  if(dist=="RecoFD") dist2="Bfeed"; 
  
  TFile infile(Form("%s.root",infilename.Data()));
  TCanvas* c1 = (TCanvas*)infile.Get(Form("c%s",dist.Data()));
  TH1F* h = (TH1F*)c1->GetPrimitive(Form("hMassPtImpPar%s_proj_2",dist2.Data()));
  h->SetDirectory(0);
  h->GetFunction(funcname)->SetBit(TF1::kNotDraw);
  h->Sumw2();
  h->Scale(1./h->Integral());
  h->SetLineColor(kRed);
  h->SetMarkerColor(kRed);
  h->SetMarkerStyle(20);
  infile.Close();

  TFile infilePtRew(Form("%s.root",infilenamePtRew.Data()));
  TCanvas* c2 = (TCanvas*)infilePtRew.Get(Form("c%s",dist.Data()));
  TH1F* hPtRew = (TH1F*)c2->GetPrimitive("hImpParReweighted");
  hPtRew->SetDirectory(0);
  hPtRew->GetFunction(funcname)->SetBit(TF1::kNotDraw);
  hPtRew->Sumw2();
  hPtRew->Scale(1./hPtRew->Integral());
  hPtRew->SetLineColor(kBlue);
  hPtRew->SetMarkerColor(kBlue);
  hPtRew->SetMarkerStyle(22);
  infilePtRew.Close();
  h->GetXaxis()->SetLabelSize(0.05);
  h->GetYaxis()->SetLabelSize(0.05);
  h->GetYaxis()->SetTitle("Normalised entries");
  Double_t mean = h->GetMean();
  Double_t errmean = h->GetMeanError();
  Double_t RMS = h->GetRMS();
  Double_t errRMS = h->GetRMSError();
  Double_t meanPtRew = hPtRew->GetMean();
  Double_t errmeanPtRew = hPtRew->GetMeanError();
  Double_t RMSPtRew = hPtRew->GetRMS();
  Double_t errRMSPtRew = hPtRew->GetRMSError();  
  TPaveText *lat = new TPaveText(0.24,0.68,0.4,0.88,"NDC");
  lat->SetFillColor(kWhite);
  lat->SetFillStyle(0);
  lat->SetBorderSize(0);
  lat->SetTextColor(kRed);
  lat->SetTextSize(0.05);
  lat->SetTextFont(132);
  lat->AddText("W/o #it{p}_{T} reweight");
  lat->AddText(Form("Mean = %0.2f #pm %0.2f",mean,errmean));
  lat->AddText(Form("RMS = %0.2f #pm %0.2f",RMS,errRMS));
  TPaveText *latPtRew = new TPaveText(0.66,0.68,0.82,0.88,"NDC");
  latPtRew->SetFillColor(kWhite);
  latPtRew->SetFillStyle(0);
  latPtRew->SetBorderSize(0);
  latPtRew->SetTextColor(kBlue);
  latPtRew->SetTextSize(0.05);
  latPtRew->SetTextFont(132);
  latPtRew->AddText("With #it{p}_{T} reweight");
  latPtRew->AddText(Form("Mean = %0.2f #pm %0.2f",meanPtRew,errmeanPtRew));
  latPtRew->AddText(Form("RMS = %0.2f #pm %0.2f",RMSPtRew,errRMSPtRew));
  
  TCanvas* c = new TCanvas("c","",800,800);
  c->SetLogy();
  TPad *pad1 = new TPad("pad1","pad1",0,0.35,1,1);
  pad1->SetBottomMargin(0);
  pad1->Draw();
  pad1->SetLogy();
  pad1->cd();
  h->GetYaxis()->SetTitleSize(0.06);
  h->GetYaxis()->SetRangeUser(0.00002,h->GetMaximum()*6);
  h->GetXaxis()->SetRangeUser(d0min,d0max);
  h->GetXaxis()->SetNdivisions(508,kTRUE);
  h->GetYaxis()->SetTitleOffset(1.2);
  h->SetTitle(Form("%0.f < #it{p}_{T} < %0.f GeV/c", pTmin, pTmax));
  h->SetStats(kFALSE);
  hPtRew->SetStats(kFALSE);
  h->Draw("E1");
  hPtRew->Draw("E1same");
  lat->Draw("same");
  latPtRew->Draw("same");
  c->cd();
  TH1F* hRatio = (TH1F*)hPtRew->Clone();
  hRatio->Divide(hPtRew,h,1.,1.);
  for(Int_t iBin=0; iBin<hRatio->GetNbinsX(); iBin++) {  
    hRatio->SetBinError(iBin+1,1.e-10);
  }
  hRatio->GetYaxis()->SetRangeUser(0.75,1.25);
  hRatio->SetTitle("");
  hRatio->GetYaxis()->SetTitle("#frac{reweighted}{not reweighted}   ");
  hRatio->GetXaxis()->SetTitleSize(0.11);
  hRatio->GetYaxis()->SetTitleSize(0.11);
  hRatio->GetXaxis()->SetLabelSize(0.1);
  hRatio->GetYaxis()->SetLabelSize(0.1);
  hRatio->GetYaxis()->SetTitleOffset(0.6);
  hRatio->GetYaxis()->SetNdivisions(505);
  hRatio->GetXaxis()->SetRangeUser(d0min,d0max);
  hRatio->GetYaxis()->SetRangeUser(ratiomin,ratiomax);
//  hRatio->SetMarkerStyle(20);
  TPad *pad2 = new TPad("pad2","pad2",0.,0.,1,0.35);
  pad2->SetTopMargin(0);
  pad2->SetBottomMargin(0.3);
  pad2->Draw();
  pad2->cd();
  hRatio->Draw("same");
    
  c->SaveAs(outfilename.Data());
}
